language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=4-7.2
    - WP4=4.9.4
    - BASE_IMAGE_STABILITY_TAG=4.2.0
  matrix:
    - TAG=4-7.2 WP_VER="${WP4}" PHP_VER=7.2
    - TAG=4-7.1 WP_VER="${WP4}" PHP_VER=7.1
    - TAG=4-7.0 WP_VER="${WP4}" PHP_VER=7.0
    - TAG=4-5.6 WP_VER="${WP4}" PHP_VER=5.6

script:
  - set -e
  - cd ./"${WP_VER:0:1}"
  - make compare-orig-configs
  - make
  - make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis_release"
