language: python

sudo: required

services:
  - docker

env:
  global:
    - LATEST_WORDPRESS=4
    - LATEST_PHP_VER=7.1
  matrix:
    - WORDPRESS=4 PHP_VER=7.1
    - WORDPRESS=4 PHP_VER=7.0
    - WORDPRESS=4 PHP_VER=5.6

script:
  - cd ./$WORDPRESS/$PHP_VER
  - make && make test

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    make release

    if [ -n "$TRAVIS_TAG" ]; then
      make TAG="$WORDPRESS-$PHP_VER-$TRAVIS_TAG" release
    fi

    if [ "$WORDPRESS" == "$LATEST_WORDPRESS" && "$PHP_VER" == "$LATEST_PHP_VER" ]; then
      make TAG=latest release
    fi
  fi
