language: bash

services:
  - docker

env:
  global:
    - CURRENT_VERSION=5.0
  matrix:
    - WORDPRESS_VER="${CURRENT_VERSION}" PHP_VER=7.3 TAGS=5-7.3,5-7,5,latest
    - WORDPRESS_VER="${CURRENT_VERSION}" PHP_VER=7.2 TAGS=5-7.2
    - WORDPRESS_VER="${CURRENT_VERSION}" PHP_VER=7.1 TAGS=5-7.1
    - WORDPRESS_VER="${CURRENT_VERSION}" PHP_VER=5.6 TAGS=5-5.6

script:
  - set -e
  - cd "${WORDPRESS_VER%%.*}"
  - make check-configs
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
