language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=4-7.2
    - WP4=4.9.4
  matrix:
    - TAG=4-7.2 WP_VER="${WP4}" PHP_VER=7.2
    - TAG=4-7.1 WP_VER="${WP4}" PHP_VER=7.1
    - TAG=4-7.0 WP_VER="${WP4}" PHP_VER=7.0
    - TAG=4-5.6 WP_VER="${WP4}" PHP_VER=5.6
    - TAG=4-7.2-dev WP_VER="${WP4}" PHP_VER=7.2 PHP_DEV=1
    - TAG=4-7.1-dev WP_VER="${WP4}" PHP_VER=7.1 PHP_DEV=1
    - TAG=4-7.0-dev WP_VER="${WP4}" PHP_VER=7.0 PHP_DEV=1
    - TAG=4-5.6-dev WP_VER="${WP4}" PHP_VER=5.6 PHP_DEV=1

script:
  - set -e
  - cd ./"${WP_VER:0:1}"
  - make compare-orig-configs
  - make
  - make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis_release"
