language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.10.0
    - WORDPRESS5=5.0
  matrix:
    - WORDPRESS_VER="${WORDPRESS5}" PHP_VER=7.3 TAGS=5-7.3,5-7,5,latest
    - WORDPRESS_VER="${WORDPRESS5}" PHP_VER=7.2 TAGS=5-7.2
    - WORDPRESS_VER="${WORDPRESS5}" PHP_VER=7.1 TAGS=5-7.1
    - WORDPRESS_VER="${WORDPRESS5}" PHP_VER=5.6 TAGS=5-5.6

script:
  - set -e
  - make check-configs
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
