language: bash

services:
  - docker

env:
  global:
    - BASE_IMAGE_STABILITY_TAG=4.8.1
    - WORDPRESS4=4.9.8
  matrix:
    - WORDPRESS_VER="${WORDPRESS4}" PHP_VER=7.2 TAGS=4-7.2,4,latest
    - WORDPRESS_VER="${WORDPRESS4}" PHP_VER=7.1 TAGS=4-7.1
    - WORDPRESS_VER="${WORDPRESS4}" PHP_VER=5.6 TAGS=4-5.6

script:
  - set -e
  - cd "${WORDPRESS_VER%%.*}"
  - make check-configs
  - make
  - make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release.sh"
