language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=4-7.2
    - BASE_IMAGE_STABILITY_TAG=3.4.0
  matrix:
    - TAG=4-7.2 WORDPRESS_VER=4 PHP_VER=7.2
    - TAG=4-7.1 WORDPRESS_VER=4 PHP_VER=7.1
    - TAG=4-7.0 WORDPRESS_VER=4 PHP_VER=7.0
    - TAG=4-5.6 WORDPRESS_VER=4 PHP_VER=5.6
    - TAG=4-7.2-dev WORDPRESS_VER=4 PHP_VER=7.2 PHP_DEV=1
    - TAG=4-7.1-dev WORDPRESS_VER=4 PHP_VER=7.1 PHP_DEV=1
    - TAG=4-7.0-dev WORDPRESS_VER=4 PHP_VER=7.0 PHP_DEV=1
    - TAG=4-5.6-dev WORDPRESS_VER=4 PHP_VER=5.6 PHP_DEV=1

script:
  - cd ./"${WORDPRESS_VER}"
  - make && make test

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ("${TRAVIS_BRANCH}" == "master"  || -n "${TRAVIS_TAG}") ]]; then
    docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

    if [[ -n "${TRAVIS_TAG}" ]]; then
      export STABILITY_TAG="${TRAVIS_TAG}"
    fi

    make release

    if [[ "${TAG}" == "${LATEST_TAG}" ]]; then
      make release TAG="latest"
    fi
  fi

notifications:
  on_failure: never
  slack:
    secure: |
      H/UFKL2raIkn2UI38tUDDV/WlvJiuGvbFT11Fll4LYQJJ7/adJnpmGRPtw3HinwiELLGaPTew/3wK0Ec4w8Ut4pcmvy5qwNZyDMafTNwHYUnPazlmfI4eJQbhMwEm6hUXD+UjJvUvIosQisHzrsryOiMzldqESKX69U/RIRYewecBW2SsqnhP8q8sjgsnXCJOT1M9lHeKbEUJTxagdT0D2PojRu+FMOz2DfviyqEiOWcokwPAYYz49J6G6BfW9vaV1uBfGof5KSAPEZgQea8kQHMc7Wmyr8bivS/Sab9jt8HwJ7o/6259zleP90o4aAabzU8yz7sP6+U+jwHG5HFg/eot2DAdnY+LKB2q8QjcvTOz5yzKUkchlnj4QflwI/5TClM+qjCiBBZk3Fq+7x46sclO5fJuzMfDRswPWjX1lB8Z2SSQqEzPABnyP9N4KRJ4LaZJi6Lu+xZBx+TBxYbXg5qUKFCS4sNdc3M7FEuzG4HkAUJTMdLDSX6entiWTFol8eShe0P3afL0V5eShbO4wgG0Pn1pEsbvrrPcXEuMdUVQD/aRHbsOwWeK9L4EEdVr8rR6autGZQla2GIIIi2nJFqI+7eSGUaJlmJ9CQ9Dcmj7jaRN2av1L8/FX428JGitxV7Q9JS//yWdZ8TV2UAp4Kt4lOlQBIntFNa4G7nhHY=