language: bash

sudo: required

services:
  - docker

env:
  global:
    - DOCKER_VERSION=17.06.2
    - LATEST_TAG=4-7.2
    - FROM_STABILITY_TAG=
  matrix:
    - WORDPRESS=4 PHP_VER=7.2
    - WORDPRESS=4 PHP_VER=7.1
    - WORDPRESS=4 PHP_VER=7.0
    - WORDPRESS=4 PHP_VER=5.6
    - WORDPRESS=4 PHP_VER=7.2 PHP_DEV=1
    - WORDPRESS=4 PHP_VER=7.1 PHP_DEV=1
    - WORDPRESS=4 PHP_VER=7.0 PHP_DEV=1
    - WORDPRESS=4 PHP_VER=5.6 PHP_DEV=1

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce="${DOCKER_VERSION}~ce-0~ubuntu"

script:
  - cd ./"${WORDPRESS}"
  - make && make test

after_success: |
  if [[ "${TRAVIS_PULL_REQUEST}" == "false" && ("${TRAVIS_BRANCH}" == "master"  || -n "${TRAVIS_TAG}") ]]; then
    docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"

    if [[ -n "${TRAVIS_TAG}" ]]; then
      export STABILITY_TAG="${TRAVIS_TAG}"
    fi

    make release

    if [[ "${TAG}" == "${LATEST_TAG}" ]]; then
      make release TAG="latest"
    fi
  fi
